# Generated by Django 3.1.2 on 2020-10-13 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onibus', '0001_initial'),
        ('principal_ponto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto',
            name='onibus',
            field=models.ManyToManyField(to='onibus.Onibus'),
        ),
    ]
