# Generated by Django 3.1.2 on 2020-10-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0001_initial'),
        ('principal_ponto', '0002_ponto_onibus'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto',
            name='horario',
            field=models.ManyToManyField(to='horario.Horario'),
        ),
    ]
